export const EMAIL_FORM = 'EMAIL_FORM';
export const EMAIL_FORM_FAILED = 'EMAIL_FORM_FAILED';
export const EMAIL_FORM_SUBMITTED = 'EMAIL_FORM_SUBMITTED';

export const PASSWORD_FORM_VISIT = 'PASSWORD_FORM_VISIT';
export const CHECKING_TOKEN = 'CHECKING_TOKEN';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const PASSWORD_FORM = 'PASSWORD_FORM';
export const PASSWORD_FORM_FAILED = 'PASSWORD_FORM_FAILED';
export const PASSWORD_IS_SET = 'PASSWORD_IS_SET';
